### ISSUE TITLE
blksnap DKMS module not available on Ubuntu 24.04.4 with kernel 6.17.0 for Google Cloud Platform (GCP)

### ISSUE THREAD

**Issue by DanielRaapDev** [veeam/blksnap#111]
### Distribution

Ubuntu 24.04.4 LTS

### Architecture

amd64

### Kernel version

6.17.0 from Ubuntu package linux-image-gcp (6.17.0-1008.8~24.04.1)

### Blksnap version

6.3.2.1207 dkms

### Bug description

We wanted to upgrade our Ubuntu packages. But the setup of the kernel failed due to dkms not able to compile the blksnap module.

apt output:
```
Setting up linux-headers-6.17.0-1008-gcp (6.17.0-1008.8~24.04.1) ...
/etc/kernel/header_postinst.d/dkms:
 * dkms: running auto installation service for kernel 6.17.0-1008-gcp
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der

Building module:
Cleaning build area...
make -j2 KERNELRELEASE=6.17.0-1008-gcp -j2 -C /lib/modules/6.17.0-1008-gcp/build M=/var/lib/dkms/blksnap/6.3.2.1207/build modules...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.17.0-1008-gcp (x86_64)
Consult /var/lib/dkms/blksnap/6.3.2.1207/build/make.log for more information.
dkms autoinstall on 6.17.0-1008-gcp/x86_64 failed for blksnap(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
 * dkms: autoinstall for kernel 6.17.0-1008-gcp
   ...fail!
run-parts: /etc/kernel/header_postinst.d/dkms exited with return code 11
dpkg: error processing package linux-headers-6.17.0-1008-gcp (--configure):
 installed linux-headers-6.17.0-1008-gcp package post-installation script subprocess returned error exit status 11
[...]

```

Excerpt from /var/lib/dkms/blksnap/6.3.2.1207/build/make.log:
```
log.c:11:10: fatal error: linux/blk_snap.h: No such file or directory
   11 | #include <linux/blk_snap.h>
      |          ^~~~~~~~~~~~~~~~~~
[...]
bdevfilter.c:372:2: error: #error "Your kernel is too old for this module."
  372 | #error "Your kernel is too old for this module."
      |  ^~~~~
bdevfilter.c:374:1: error: expected identifier or ‘(’ before ‘{’ token
  374 | {
      | ^
In file included from /usr/src/linux-headers-6.17.0-1008-gcp/include/linux/linkage.h:7,
[...]
                 from bdevfilter.c:3:
bdevfilter.c:381:15: error: ‘submit_bio_noacct_notrace’ undeclared here (not in a function); did you mean ‘submit_bio_noacct’?
  381 | EXPORT_SYMBOL(submit_bio_noacct_notrace);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~
[...]
```

### Steps to reproduce

Update kernel headers with `apt install linux-headers-gcp`.
> Unpacking linux-headers-gcp (6.17.0-1008.8~24.04.1) over (6.14.0-1021.22~24.04.1) ...

See https://packages.ubuntu.com/noble/linux-image-gcp for current version of actual package.

### Expected behavior

The module compiles with a current Ubuntu kernel.

### Additional information

Maybe the same as #106 ?

**Comment by DanielRaapDev** [comment]
[make.log](https://github.com/user-attachments/files/25545600/make.log)

**Comment by SergeiShtepa** [comment]
Hi!
Yes. That's right.
See [compatibility notes for 6.3.2](https://github.com/veeam/blksnap/tree/VAL-6.3.2?tab=readme-ov-file#compatibility-notes).
LK 6.15 is not supported for VAL 6.3.2.
And read [release notes](https://helpcenter.veeam.com/rn/veeam_agent_linux_6_3_2_release_notes.html), please.
This porblem fixed. See [comment](https://github.com/veeam/blksnap/commit/6c4131abb3aa6c1393b318944d843ded21f3d65b).
You can use 13.0.1 version of Veeam Agent for Linux. It support linux kernel 6.18. See [notes](https://helpcenter.veeam.com/rn/veeam_backup_13_0_1_release_notes.html#system-requirements-workloads-physical-and-cloud-backup-veeam-agent-for-linux-operating-systems).

**Comment by DanielRaapDev** [comment]
Thanks for the hints.
