### ISSUE TITLE
Error! Bad return status for module build on kernel: 6.17.2-2-pve (x86_64)

### ISSUE THREAD

**Issue by DimiDr0l** [veeam/blksnap#109]
`dkms autoinstall -k 6.17.2-2-pve
Sign command: /lib/modules/6.17.2-2-pve/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Autoinstall of module blksnap/6.3.2.1207 for kernel 6.17.2-2-pve (x86_64)
Building module(s)...(bad exit status: 2)
Failed command:
make -j16 KERNELRELEASE=6.17.2-2-pve -j16 -C /lib/modules/6.17.2-2-pve/build M=/var/lib/dkms/blksnap/6.3.2.1207/build modules

Error! Bad return status for module build on kernel: 6.17.2-2-pve (x86_64)
Consult /var/lib/dkms/blksnap/6.3.2.1207/build/make.log for more information.

Autoinstall on 6.17.2-2-pve failed for module(s) blksnap(10).

Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.`

`
cat /var/lib/dkms/blksnap/6.3.2.1207/build/make.log
DKMS (dkms-3.2.2) make.log for blksnap/6.3.2.1207 for kernel 6.17.2-2-pve (x86_64)
Thu Nov 27 10:38:33 PM MSK 2025

Building module(s)
# command: make -j16 KERNELRELEASE=6.17.2-2-pve -j16 -C /lib/modules/6.17.2-2-pve/build M=/var/lib/dkms/blksnap/6.3.2.1207/build modules
make: Entering directory '/usr/src/linux-headers-6.17.2-2-pve'
make[1]: Entering directory '/var/lib/dkms/blksnap/6.3.2.1207/build'
  CC [M]  bdevfilter.o
  CC [M]  log.o
  CC [M]  log_histogram.o
  CC [M]  big_buffer.o
  CC [M]  cbt_map.o
  CC [M]  chunk.o
  CC [M]  ctrl.o
  CC [M]  diff_io.o
  CC [M]  diff_area.o
  CC [M]  diff_buffer.o
  CC [M]  diff_storage.o
  CC [M]  event_queue.o
  CC [M]  main.o
  CC [M]  snapimage.o
  CC [M]  snapshot.o
  CC [M]  sysfs.o
diff_storage.c:10:10: fatal error: linux/blk_snap.h: No such file or directory
   10 | #include <linux/blk_snap.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: diff_storage.o] Error 1
make[3]: *** Waiting for unfinished jobs....
snapshot.c:8:10: fatal error: linux/blk_snap.h: No such file or directory
    8 | #include <linux/blk_snap.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: snapshot.o] Error 1
cbt_map.c:7:10: fatal error: linux/blk_snap.h: No such file or directory
    7 | #include <linux/blk_snap.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: cbt_map.o] Error 1
ctrl.c:11:10: fatal error: linux/blk_snap.h: No such file or directory
   11 | #include <linux/blk_snap.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: ctrl.o] Error 1
log.c:11:10: fatal error: linux/blk_snap.h: No such file or directory
   11 | #include <linux/blk_snap.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: log.o] Error 1
main.c:7:10: fatal error: linux/blk_snap.h: No such file or directory
    7 | #include <linux/blk_snap.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: main.o] Error 1
bdevfilter.c:372:2: error: #error "Your kernel is too old for this module."
  372 | #error "Your kernel is too old for this module."
      |  ^~~~~
bdevfilter.c:374:1: error: expected identifier or ‘(’ before ‘{’ token
  374 | {
      | ^
snapimage.c:9:10: fatal error: linux/blk_snap.h: No such file or directory
    9 | #include <linux/blk_snap.h>
      |          ^~~~~~~~~~~~~~~~~~
diff_io.c: In function ‘diff_io_do’:
compilation terminated.
diff_io.c:180:40: error: passing argument 1 of ‘bio_alloc_bioset’ makes pointer from integer without a cast [-Wint-conversion]
  180 |                 bio = bio_alloc_bioset(gfp, nr_iovecs, &diff_io_bioset);
      |                                        ^~~
      |                                        |
      |                                        gfp_t {aka unsigned int}
In file included from /usr/src/linux-headers-6.17.2-2-pve/include/linux/blkdev.h:17,
                 from diff_io.c:6:
/usr/src/linux-headers-6.17.2-2-pve/include/linux/bio.h:356:51: note: expected ‘struct block_device *’ but argument is of type ‘gfp_t’ {aka ‘unsigned int’}
  356 | struct bio *bio_alloc_bioset(struct block_device *bdev, unsigned short nr_vecs,
      |                              ~~~~~~~~~~~~~~~~~~~~~^~~~
diff_io.c:180:56: error: passing argument 3 of ‘bio_alloc_bioset’ makes integer from pointer without a cast [-Wint-conversion]
  180 |                 bio = bio_alloc_bioset(gfp, nr_iovecs, &diff_io_bioset);
      |                                                        ^~~~~~~~~~~~~~~
      |                                                        |
      |                                                        struct bio_set *
/usr/src/linux-headers-6.17.2-2-pve/include/linux/bio.h:357:40: note: expected ‘blk_opf_t’ {aka ‘unsigned int’} but argument is of type ‘struct bio_set *’
  357 |                              blk_opf_t opf, gfp_t gfp_mask,
      |                              ~~~~~~~~~~^~~
diff_io.c:180:23: error: too few arguments to function ‘bio_alloc_bioset’
  180 |                 bio = bio_alloc_bioset(gfp, nr_iovecs, &diff_io_bioset);
      |                       ^~~~~~~~~~~~~~~~
/usr/src/linux-headers-6.17.2-2-pve/include/linux/bio.h:356:13: note: declared here
  356 | struct bio *bio_alloc_bioset(struct block_device *bdev, unsigned short nr_vecs,
      |             ^~~~~~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: snapimage.o] Error 1
chunk.c:21:24: error: redefinition of ‘bdev_nr_sectors’
   21 | static inline sector_t bdev_nr_sectors(struct block_device *bdev)
      |                        ^~~~~~~~~~~~~~~
In file included from chunk.h:6,
                 from chunk.c:8:
/usr/src/linux-headers-6.17.2-2-pve/include/linux/blkdev.h:824:24: note: previous definition of ‘bdev_nr_sectors’ with type ‘sector_t(struct block_device *)’ {aka ‘long long unsigned int(struct block_device *)’}
  824 | static inline sector_t bdev_nr_sectors(struct block_device *bdev)
      |                        ^~~~~~~~~~~~~~~
chunk.c: In function ‘bdev_nr_sectors’:
chunk.c:23:32: error: ‘struct block_device’ has no member named ‘bd_inode’
   23 |         return i_size_read(bdev->bd_inode) >> 9;
      |                                ^~
chunk.c: In function ‘chunk_store_failed’:
chunk.c:80:17: error: implicit declaration of function ‘LIMIT_BEGIN’ [-Wimplicit-function-declaration]
   80 |                 LIMIT_BEGIN(7)
      |                 ^~~~~~~~~~~
In file included from /usr/src/linux-headers-6.17.2-2-pve/include/asm-generic/bug.h:22,
                 from /usr/src/linux-headers-6.17.2-2-pve/arch/x86/include/asm/bug.h:103,
                 from /usr/src/linux-headers-6.17.2-2-pve/arch/x86/include/asm/alternative.h:9,
                 from /usr/src/linux-headers-6.17.2-2-pve/arch/x86/include/asm/nospec-branch.h:10,
                 from /usr/src/linux-headers-6.17.2-2-pve/arch/x86/include/asm/irqflags.h:9,
                 from /usr/src/linux-headers-6.17.2-2-pve/include/linux/irqflags.h:18,
                 from /usr/src/linux-headers-6.17.2-2-pve/include/linux/spinlock.h:59,
                 from /usr/src/linux-headers-6.17.2-2-pve/include/linux/mmzone.h:8,
                 from /usr/src/linux-headers-6.17.2-2-pve/include/linux/gfp.h:7,
                 from /usr/src/linux-headers-6.17.2-2-pve/include/linux/slab.h:16,
                 from chunk.c:3:
/usr/src/linux-headers-6.17.2-2-pve/include/linux/printk.h:484:10: error: expected expression before ‘{’ token
  484 |         ({                                                              \
      |          ^
/usr/src/linux-headers-6.17.2-2-pve/include/linux/printk.h:514:26: note: in expansion of macro ‘printk_index_wrap’
  514 | #define printk(fmt, ...) printk_index_wrap(_printk, fmt, ##__VA_ARGS__)
      |                          ^~~~~~~~~~~~~~~~~
/usr/src/linux-headers-6.17.2-2-pve/include/linux/printk.h:557:9: note: in expansion of macro ‘printk’
  557 |         printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |         ^~~~~~
chunk.c:81:17: note: in expansion of macro ‘pr_err’
   81 |                 pr_err("Failed to store chunk #%lu\n", chunk->number);
      |                 ^~~~~~
chunk.c:80:17: error: called object is not a function or function pointer
   80 |                 LIMIT_BEGIN(7)
      |                 ^~~~~~~~~~~
diff_io.c:191:17: error: implicit declaration of function ‘bio_set_op_attrs’ [-Wimplicit-function-declaration]
  191 |                 bio_set_op_attrs(bio, opf, op_flags);
      |                 ^~~~~~~~~~~~~~~~
chunk.c:82:17: error: implicit declaration of function ‘LIMIT_STOP’; did you mean ‘RLIMIT_STACK’? [-Wimplicit-function-declaration]
   82 |                 LIMIT_STOP()
      |                 ^~~~~~~~~~
      |                 RLIMIT_STACK
diff_io.c:223:17: error: implicit declaration of function ‘io_set_flag’; did you mean ‘bio_set_flag’? [-Wimplicit-function-declaration]
  223 |                 io_set_flag(bio, BIO_FILTERED);
      |                 ^~~~~~~~~~~
      |                 bio_set_flag
/usr/src/linux-headers-6.17.2-2-pve/include/linux/printk.h:484:10: error: expected expression before ‘{’ token
  484 |         ({                                                              \
      |          ^
/usr/src/linux-headers-6.17.2-2-pve/include/linux/printk.h:514:26: note: in expansion of macro ‘printk_index_wrap’
  514 | #define printk(fmt, ...) printk_index_wrap(_printk, fmt, ##__VA_ARGS__)
      |                          ^~~~~~~~~~~~~~~~~
/usr/src/linux-headers-6.17.2-2-pve/include/linux/printk.h:557:9: note: in expansion of macro ‘printk’
  557 |         printk(KERN_ERR pr_fmt(fmt), ##__VA_ARGS__)
      |         ^~~~~~
chunk.c:83:17: note: in expansion of macro ‘pr_err’
   83 |                 pr_err("Too many chunk have failed, stop flooding\n");
      |                 ^~~~~~
chunk.c:82:17: error: called object is not a function or function pointer
   82 |                 LIMIT_STOP()
      |                 ^~~~~~~~~~
In file included from /usr/src/linux-headers-6.17.2-2-pve/include/linux/linkage.h:7,
                 from /usr/src/linux-headers-6.17.2-2-pve/include/linux/printk.h:8,
                 from /usr/src/linux-headers-6.17.2-2-pve/include/asm-generic/bug.h:22,
                 from /usr/src/linux-headers-6.17.2-2-pve/arch/x86/include/asm/bug.h:103,
                 from /usr/src/linux-headers-6.17.2-2-pve/arch/x86/include/asm/alternative.h:9,
                 from /usr/src/linux-headers-6.17.2-2-pve/arch/x86/include/asm/barrier.h:5,
                 from /usr/src/linux-headers-6.17.2-2-pve/include/linux/list.h:11,
                 from /usr/src/linux-headers-6.17.2-2-pve/include/linux/module.h:12,
                 from bdevfilter.c:3:
bdevfilter.c:381:15: error: ‘submit_bio_noacct_notrace’ undeclared here (not in a function); did you mean ‘submit_bio_noacct’?
  381 | EXPORT_SYMBOL(submit_bio_noacct_notrace);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-6.17.2-2-pve/include/linux/export.h:76:23: note: in definition of macro ‘__EXPORT_SYMBOL’
   76 |         extern typeof(sym) sym;                                 \
      |                       ^~~
/usr/src/linux-headers-6.17.2-2-pve/include/linux/export.h:89:41: note: in expansion of macro ‘_EXPORT_SYMBOL’
   89 | #define EXPORT_SYMBOL(sym)              _EXPORT_SYMBOL(sym, "")
      |                                         ^~~~~~~~~~~~~~
bdevfilter.c:381:1: note: in expansion of macro ‘EXPORT_SYMBOL’
  381 | EXPORT_SYMBOL(submit_bio_noacct_notrace);
      | ^~~~~~~~~~~~~
bdevfilter.c:389:1: error: expected identifier or ‘(’ before ‘{’ token
  389 | {
      | ^
chunk.c:84:17: error: implicit declaration of function ‘LIMIT_END’ [-Wimplicit-function-declaration]
   84 |                 LIMIT_END()
      |                 ^~~~~~~~~
chunk.c:84:28: error: expected ‘;’ before ‘diff_area_set_corrupted’
   84 |                 LIMIT_END()
      |                            ^
      |                            ;
   85 |                 diff_area_set_corrupted(diff_area, error);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~
diff_area.c:11:10: fatal error: linux/blk_snap.h: No such file or directory
   11 | #include <linux/blk_snap.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
diff_io.c:223:34: error: ‘BIO_FILTERED’ undeclared (first use in this function)
  223 |                 io_set_flag(bio, BIO_FILTERED);
      |                                  ^~~~~~~~~~~~
diff_io.c:223:34: note: each undeclared identifier is reported only once for each function it appears in
chunk.c: In function ‘bdev_nr_sectors’:
chunk.c:24:1: error: control reaches end of non-void function [-Werror=return-type]
   24 | };
      | ^
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: diff_area.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: chunk.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: diff_io.o] Error 1
sysfs.c:9:10: fatal error: linux/blk_snap.h: No such file or directory
    9 | #include <linux/blk_snap.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
bdevfilter.c: In function ‘ftrace_handler_submit_bio_noacct’:
bdevfilter.c:420:62: error: ‘submit_bio_noacct_handler’ undeclared (first use in this function); did you mean ‘submit_bio_noacct_notrace’?
  420 |                 instruction_pointer_set(regs, (unsigned long)submit_bio_noacct_handler);
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              submit_bio_noacct_notrace
bdevfilter.c:420:62: note: each undeclared identifier is reported only once for each function it appears in
bdevfilter.c: At top level:
bdevfilter.c:426:17: error: initialization of ‘void (*)(long unsigned int,  long unsigned int,  struct ftrace_ops *, struct ftrace_regs *)’ from incompatible pointer type ‘void (*)(long unsigned int,  long unsigned int,  struct ftrace_ops *, struct pt_regs *)’ [-Wincompatible-pointer-types]
  426 |         .func = ftrace_handler_submit_bio_noacct,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bdevfilter.c:426:17: note: (near initialization for ‘ops_submit_bio_noacct.func’)
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: sysfs.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.17.2-2-pve/scripts/Makefile.build:287: bdevfilter.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.17.2-2-pve/Makefile:2016: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.17.2-2-pve/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/blksnap/6.3.2.1207/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.17.2-2-pve'

# exit code: 2
# elapsed time: 00:00:01
`

**Comment by SergeiShtepa** [comment]
Hi Dmitri.

See commit [fix lk6.15](https://github.com/veeam/blksnap/commit/6c4131abb3aa6c1393b318944d843ded21f3d65b).
And use latest version  [13.0.1](https://github.com/veeam/blksnap/tree/VAL-13.0.1) of the module with Veeam Agent for Linux v13.0.1.

It's should work on the Proxmox system.

**Comment by DimiDr0l** [comment]
- modinfo veeamblksnap
```
filename:       /lib/modules/6.17.2-2-pve/kernel/drivers/block/veeamblksnap.ko
supported:      external
license:        GPL
author:         Veeam Software Group GmbH
version:        7.0.0.0
description:    Block Device Snapshots Module
srcversion:     9869C12761ACB09DD547B33
depends:        bdevfilter
name:           veeamblksnap
retpoline:      Y
vermagic:       6.17.2-2-pve SMP preempt mod_unload modversions
parm:           tracking_block_minimum_shift:The power of 2 for minimum tracking block size (uint)
parm:           tracking_block_maximum_count:The maximum number of tracking blocks (uint)
parm:           tracking_block_maximum_shift:The power of 2 for maximum trackings block size (uint)
parm:           chunk_minimum_shift:The power of 2 for minimum chunk size (uint)
parm:           chunk_maximum_count_shift:The power of 2 for maximum number of chunks (uint)
parm:           chunk_maximum_shift:The power of 2 for maximum snapshots chunk size (uint)
parm:           chunk_maximum_in_queue:The maximum number of chunks in store queue (uint)
parm:           diff_storage_minimum:The minimum allowable size of the difference storage in sectors (uint)
```
- modinfo bdevfilter
```
filename:       /lib/modules/6.17.2-2-pve/kernel/drivers/block/bdevfilter.ko
supported:      external
license:        GPL
author:         Veeam Software Group GmbH
version:        7.0.0.0
description:    Block Device Filter kernel module
srcversion:     BBECE75D0E68A4C717BD01A
depends:
name:           bdevfilter
retpoline:      Y
vermagic:       6.17.2-2-pve SMP preempt mod_unload modversions
```
-  lsmod | egrep "bdevfilter|veeam"
```
veeamblksnap          151552  0
bdevfilter             98304  1 veeamblksnap
```
veeam backup:
```
      17:11:30         [error] Failed to create volume snapshot 00:00:01
      17:11:31         [error] Failed to take volume snapshot
      17:11:31         [error] Failed to perform backup
      17:11:31         [error] Inappropriate ioctl for device
      17:11:31         [error] Failed to execute IOCTL_BLK_SNAP_VERSION
      17:11:31         [error] Processing finished with errors at 2025-11-28 14:11:31 UTC

```
